version: '3'

services:

  analytics:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 33380:80
      - 38888:8888
    environment:
      SHELL: /bin/bash
    volumes:
      - "./:/code"
